### ISSUE TITLE
Evosuite_tutorial

### ISSUE THREAD

**Issue by FukumotoHaruki** [Wakayama-SocSEL/Fukumoto#3]
チュートリアルではEvosuiteをコマンドラインで行う。
- [x] javaのinstall
- [x] Apache Mavenのinstall
- [x] Evosuiteの入手
　現在jarファイルの実行に失敗している。

**Comment by FukumotoHaruki** [comment]
SocSELnoMacBook-puro-3:program Haruki-F$ java -jar evosuite-1.0.6.jar
Error: Invalid or corrupt jarfile evosuite-1.0.6.jar

「jarファイルが無効または壊れています」と表示されている。

**Comment by FukumotoHaruki** [comment]
上記の問題は解決した。

次は、以下のようなエラーが発生した。
「[MASTER] 18：12：52.354 [main]エラーEvoSuite  - メインのEvoSuiteプロセスで致命的なクラッシュが発生しました。 シードを使用するクラス1544087572351.構成ID：null
java.lang.RuntimeException：tools.jarを自動的に検索できませんでした。」（訳）
↑
SocSELnoMacBook-puro-3:Tutorial_Stack Haruki-F$ java -jar evosuite-1.0.6.jar
[MASTER] 18:18:55.030 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class  using seed 1544087935027. Configuration id : null
java.lang.RuntimeException: Did not manage to automatically find tools.jar. Use -Dtools_jar_location=<path> property
	at org.evosuite.runtime.agent.ToolsJarLocator.getLoaderForToolsJar(ToolsJarLocator.java:105) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.classpath.ClassPathHacker.initializeToolJar(ClassPathHacker.java:58) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:156) ~[evosuite-1.0.6.jar:1.0.6]
	at org.evosuite.EvoSuite.main(EvoSuite.java:302) ~[evosuite-1.0.6.jar:1.0.6]

**Comment by FukumotoHaruki** [comment]
上記のエラーは解決した。
JDKのバージョンが最新のものでは、エラーが出る様子

JDKのバージョンを1.8にすると解決した。

**Comment by FukumotoHaruki** [comment]
Evosuiteのテストスイートの生成に成功した。

**Comment by FukumotoHaruki** [comment]
Tutorial1完了！
動くことは確認できた！

**Comment by FukumotoHaruki** [comment]
# Evosuite使い方（訳）

**Comment by FukumotoHaruki** [comment]
- テスト実行時の注意
  - デフォルトでEvoSuiteはコード行だけでなく、突然変異検査などのさまざまなテスト基準を満たすことを試みるから時間がとてもかかる。
  - デフォルトでは、60秒でタイムアウトし、テストの作成を終了する。

＊既存のテストで作業することもできる。

javaのバージョン変更方法
---
/usr/libexec/java_home -Vを実行でインストールされているjavaが確認できる。
export JAVA_HOME=`/usr/libexec/java_home -v 1.7.0_45(ここは変更)`
java -version
javac -versionの順で実行

**Comment by FukumotoHaruki** [comment]
#テストの実行
